version: "3.8"
services:
    nextjsapp:
        image: jamiekariuki/nextjs-app
        ports:
            - "3000:3000"
        environment:
            - NODE_ENV=production
        volumes:
            - .:/app
        restart: always
